### ISSUE TITLE
Keymaps missing checks for sublime_enhanced_keybindings

### ISSUE THREAD

**Issue by ghost** [shagabutdinov/sublime-expression#1]
Some keymaps are still missing checks for sublime_enhanced_keybindings. For example, after installing this package I tried to comment a line by pressing ctrl+/ but this ended up doing a delete, even though I had disabled sublime_enhanced_keybindings.

**Comment by shagabutdinov** [comment]
Thank you for issue; done in 19f0b5622983ad58a928cdc49f45097f85884682.

**Comment by ghost** [comment]
I appreciate the quick response, but could you also apply the changes for the other operating systems?

**Comment by shagabutdinov** [comment]
Sorry for late response and thank you for your pull request (https://github.com/shagabutdinov/sublime-expression/pull/2) :)
